### ISSUE TITLE
docs: Refactor docs

### ISSUE THREAD

**Issue by davidhozic** [davidhozic/TkClassWizard#7]
- Fix grammar

**Comment by juliajobczyk** [comment]
Hi can I please be assigned for this? Will this be a good first issue to work on? Thanks.

**Comment by davidhozic** [comment]
> Hi can I please be assigned for this? Will this be a good first issue to work on? Thanks.

Yeah I guess, I mostly wanted to refactor the ``First steps`` (inside Guide) part as it seems a bit off to me, other stuff in the guide should be fine. The API reference is auto-generated from code and doesn't need any changes.

``docs/source/guide/firststeps.rst``

Now for building... it's not pure Sphinx but I have sort of an extension on top of it. So if you want to build it locally you would need:
- Make (for Makefile)
- Commands:
  - ``pip install .[docs]`` inside the cloned folder
  - ``cd docs``
  - ``make html``

Or you can just create a pull request, where it will be auto built. Create a fork of repository first, edit there and then create a pull request.

**Comment by juliajobczyk** [comment]
I think this may be a little bit over my abilities, I'm still new to this, sorry for wasting your time.

**Comment by davidhozic** [comment]
> I think this may be a little bit over my abilities, I'm still new to this, sorry for wasting your time.

That's ok, you didn't really waste my time.

**Comment by vjurcutiu** [comment]
Hey David, I'd like to help out, if the issue is still open.

**Comment by davidhozic** [comment]
> Hey David, I'd like to help out, if the issue is still open.

Sure

**Comment by vjurcutiu** [comment]
Thanks, I'll keep you updated.

**Comment by vjurcutiu** [comment]
Hi @davidhozic, I have opened the PR. Let me know if it needs any other changes.

**Comment by davidhozic** [comment]
lgtm, merged. Thank you!
